### ISSUE TITLE
Mineral fields and gas geysers do not reset correctly

### ISSUE THREAD

**Issue by tockar** [benchmarker/benchmarker#412]
On the new Benchmarker (Dusk Towers) map the mineral fields which contain 900 minerals are not reset to the default (900) mineral value, instead they stay on the values before hitting the reset button. This bug does not affect 1500 mineral fields. 

The same bug is affecting gas geysers - they do not reset to the default (2000) values after hitting the reset button.

**Comment by bsaffel** [comment]
Thanks tockar,  I will take a look at this today and see if I can get it fixed by this evening.
